### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by klokan** [hfu/africa-pure-osm-1712#1]
This repository contain vector tiles generated from OpenStreetMap data using OpenMapTiles Schema - the data and vector tile schema have clear license conditions - which you can't waive.

As such the claimed LICENSE ("The Unlicense" = public domain) is incorrect. Please fix it.

The repo contains from 99% the data - not software. If people download or display the data (generated vector tiles) from your github repository they must follow conditions different then mentioned in your LICENSE file. 

The license must specify the required attribution for both OpenStreetMap and OpenMapTiles. Probably something like a text derived from https://github.com/openmaptiles/openmaptiles/blob/master/LICENSE.md#design-license-cc-by-40:

# ODBL + CC-BY 4.0

Vector tiles derived from OpenStreetMap open data, licensed under the Open Data Commons Open Database License (ODbL) by the OpenStreetMap Foundation (OSMF). http://www.openstreetmap.org/copyright

The cartography and visual design features of the map tile schema are licensed under the Creative Commons Attribution 4.0 license.
To view a copy of the license, visit http://creativecommons.org/licenses/by/4.0/.

Products or services using maps derived from OpenMapTiles schema need to visibly
credit "OpenMapTiles.org" or reference "OpenMapTiles" with a link to
http://openmaptiles.org/.

For a browsable electronic map based on OpenMapTiles and OpenStreetMap data, the
credit should appear in the corner of the map. For example:

[© OpenMapTiles](http://openmaptiles.org/) [© OpenStreetMap contributors](http://www.openstreetmap.org/copyright)

For printed and static maps a similar attribution should be made in a textual
description near the image, in the same fashion as if you cite a photograph.

Exceptions to OpenMapTiles attribution requirement can be in a written form granted
by Klokan Technologies GmbH (info@klokantech.com).  
The project contributors grant Klokan Technologies GmbH the license to give such
exceptions on a commercial basis.

**Comment by klokan** [comment]
Could you please assign a correct license with attributtion also to all other vector tilesets you create, such as:
https://gitlab.com/hfujimura/uga1801/ etc.

Thank you!

**Comment by hfu** [comment]
Hi! First of all, thank you very much for your great work with OpenMapTiles and other great products!

I have no objection to your point. As a urgent response, I modified https://github.com/hfu/africa-pure-osm-1712/blob/master/LICENSE.md . My aim is to keep the license of the prior works, and keep my contribution 'public domain'. (This might mean my name is not included in the copyright holder of the derived product. I need to make clear how I can do this.) I need to clarify this, and need to include the copyright holder of the CC-BY components. I will develop more proper license documentation and update the LICENSE.md. 

By the way, I added the "© OpenMapTiles © OpenStreetMap contributors" attribution to the browsing site such as in https://hfu.github.io/uga1801-bright/ . I admit this does not make the correct LICENSE.md necessary at those vector tile data repository.

Anyway, I will get back to you soon after further development.

Thank you, and I will get back to you here soon!

**Comment by klokan** [comment]
Thank you! A pleasure to see our OpenMapTiles and other projects used...

**Comment by hfu** [comment]
Thank you, @klokan !

I would like to finalize the LICENCE.md for my vector tiles repositories as the following, citing all the text up to "The project contributors grant Klokan Technologies GmbH the license to give such
exceptions on a commercial basis." plus added "Klokan Technologies GmbH" as "by whom" of CC-BY 4.0 . I really appreciate if you could shortly review https://github.com/hfu/africa-pure-osm-1712/blob/master/LICENSE.md .

For other vector tiles repositories I produced, I will add this LICENCE.md right now. I will track these changes at https://github.com/hfu/osm-countries/issues/1 .

Thank you!
